### ISSUE TITLE
requirements for sim cfg

### ISSUE THREAD

**Issue by EvgenyKusmenko** [MontiSim/simulation#2]

**Comment by pbilov** [comment]
Configuration requirements for:

1. World/global settings
#map main settings
- map=<path to map osm file on disk>
- mapName=<map name to be associated in DB with map file>
- flat_map=<map terrain mode: 1 -> ALLZERO, otherwise RANDOM> #can be changed to use enum
- weather_rain=<world weather: 1 -> RAIN, otherwise SUNSHINE>
#sector map settings
- map_overlap=<overlapped area size (2d)>
- map_sector_width=<sectors width>
- map_sector_length=<sectors height>
#sector server settings
- max_sector_users=<max number of users OR spectators per sector, e.g. 5 means 5 users and 5 specators>
- max_limbo=<max user limbo time. If exceeded, user is disconnected>
#simulation settings
- sim_loop_freq=<simulation loop frequence>
- sim_duration=<simulation duration in frames>
- sim_type=<fixed, real-time, max-fps, TO BE discussed>

2. Simulation scenario
- scenarioName=<meaningful name of the scenario>
- scenarioTracks=<list of tracks>
  - trackName=<meaningful name of the route - for future customization of configuration>
  - startX=<start point X coordinate>
  - startY=<start point Y coordinate>
  - endX=<end point X coordinate>
  - endY=<end point Y coordinate>

**Comment by EvgenyKusmenko** [comment]
- ways ways of defining cars pos : x,y,(z),phi=rot (+ random)  OR nodeID = automatically rotated vehicle , completely random,

**Comment by DeltaBoss** [comment]
@pbilov : Did you intend 1 and 2 to be in different files?

**Comment by pbilov** [comment]
@DeltaBoss 
- It does not matter whether we use multiple files or not. Currently it is a single file
- _map_overlap_ is a **number**, defining width or height of overlapped area between two sectors. When such areas are computed, the width/height is implicitly obtained from the sector's dimensions and height/width from this parameter.
- sectors' size does not take units
